### ISSUE TITLE
homepage URL

### ISSUE THREAD

**Issue by hxrts** [cosmos/chain-registry#150]
This is more a convenience thing, but it could be good to optionally link a public URL so clients can look that up. Could also go one step further and include a public key + URL/pubkey.txt, so the webmaster can attest that the website is authenticated by on-chain gov.

Negative here is if projects opt to do this they are enshrining an official page that could imply singular control.

**Comment by faddat** [comment]
The chain should have a web server & a front end, ala:

app.osmosis.zone
blurt.blog

**Comment by nooomski** [comment]
I personally think this can be complicated in terms of demonstrating decentralization. We have a Cosmos page, because the stack is built by several organizations that ICF funds, but we don't have an official Cosmos Hub website, because nobody owns the Cosmos Hub. We can leave it as an optional field, but I don't think we should make it a requirement.

**Comment by faddat** [comment]
I'm with Sam on this, a web site is important-- just I think that it should be served from a chain.

**Comment by hxrts** [comment]
leaving it optional and using an array works for me

**Comment by JeremyParish69** [comment]
We can probably pull a lot of this from the SLIP 173 registration to get started.
https://github.com/satoshilabs/slips/blob/master/slip-0173.md

**Comment by hxrts** [comment]
https://github.com/cosmos/chain-registry/issues/524
