### ISSUE TITLE
duplicated tokens on chain-registry

### ISSUE THREAD

**Issue by marslavish** [cosmos/chain-registry#1535]
For example, there're two ATOM tokens, one is the governance token on Carbon:
![image](https://user-images.githubusercontent.com/37969603/222334437-3d3fb97b-47bb-4e3f-9ca7-530242dd68fe.png)
and the other is the native token of the Cosmos Hub
![image](https://user-images.githubusercontent.com/37969603/222335175-ae71d658-d67c-4c9f-a4a6-52f633d970de.png)

**Comment by pyramation** [comment]
I find it odd we're including IBC denoms in the asset list?

https://github.com/cosmos/chain-registry/blob/a0d00237dfa11087c6b34b8b5a5435eb24f685ab/carbon/assetlist.json#L484

cc @JeremyParish69

**Comment by pyramation** [comment]
@JeremyParish69 for persistence, this is fine, because we handled the special case. However, we should be using the [`npm` module](https://github.com/cosmology-tech/chain-registry) for generating IBC denoms... or maybe we can look at other solutions. But currently this type of asset list is creating duplicates. I would suggest we only include "native" tokens in the assetlist, or we make an ibcassets.json that has these tokens that aren't meant to be "native".

The

**Comment by pyramation** [comment]
<img width="390" alt="Screen Shot 2023-03-01 at 10 31 39 PM" src="https://user-images.githubusercontent.com/545047/222339665-4f2a86de-bf97-49da-859a-1df77ff688f1.png">

**Comment by JeremyParish69** [comment]
Proposed solution is to add another asset type 'ics_20' https://github.com/cosmos/chain-registry/pull/1538

**Comment by JeremyParish69** [comment]
This can now be filtered by the 'ics20' value for the type_asset enum
