### ISSUE TITLE
Terra chains 

### ISSUE THREAD

**Issue by emidev98** [cosmos/chain-registry#3224]
Hello, I wanted to check with you before submitting the PR. If I submit a PR changing the current `terra` identifiers to `terra-classic` and `terra2` to `terra`, would it be accepted? Terra phoenix-1, the chain was never meant to be branded at Terra2, and this can misslead users. I already submitted some prs to other repos like the one for ping.pub, to start harmonizing everything everywhere. Thanks!

**Comment by JeremyParish69** [comment]
No I don't think we should change this. The chain_name is meant to be permanent (expect some testnets have changed) and any change could have far reaching consequences due to the dependencies that exist. The chain_name terra2 is only meant to be a Registry key, and nothing that end users should be exposed to.

**Comment by emidev98** [comment]
Thank you for the answer @JeremyParish69, it makes a lot of sense to be a key identifier and a very important value that shouldn't be mutable.
